### ISSUE TITLE
Cannot find settings

### ISSUE THREAD

**Issue by newton108** [Arcath/jekyll-atom#9] opened 2015-01-16 04:11 UTC
I'm using atom 0.174.0. Cannot find settings under the package.
![screen shot 2015-01-16 at 04 10 21](https://cloud.githubusercontent.com/assets/3450659/5771471/aec1956e-9d35-11e4-8ea7-7e13befc870d.png)

**Comment by Arcath** [comment] 2015-01-19 13:39
I've just updated to 0.174.0 and can confirm that the settings do not appear. Will do some testing now

**Comment by Arcath** [comment] 2015-02-04 14:58
This is caused by this bug: https://github.com/atom/settings-view/issues/356

If you activate the package by opening anything (I suggest the new post window then close it) the settings will now appear

**Comment by Arcath** [comment] 2015-07-14 10:44
This was fixed in atom

**Closed by Arcath** 2015-07-14 10:44 UTC
