### ISSUE TITLE
Uncaught YAMLException: duplicated mapping key at line 77, column 1:        ^

### ISSUE THREAD

**Issue by thatguychrisw** [Arcath/jekyll-atom#50] opened 2016-04-07 14:20 UTC
[Enter steps to reproduce below:]
1. Click Packages -> Jekyll -> New Post

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.3
**Thrown From**: [jekyll](https://github.com/arcath/jekyll-atom) package, v1.4.0
### Stack Trace

Uncaught YAMLException: duplicated mapping key at line 77, column 1:

```
^
```

```
At /Users/developer/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168

YAMLException: duplicated mapping key at line 77, column 1:

    ^
    at generateError (/Users/developer/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/developer/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at storeMappingPair (/Users/developer/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:305:7)
    at readBlockMapping (/Users/developer/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1065:9)
    at composeNode (/Users/developer/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/Users/developer/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/Users/developer/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at load (/Users/developer/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at Object.safeLoad (/Users/developer/.atom/packages/jekyll/node_modules/js-yaml/lib/js-yaml/loader.js:1579:10)
    at Object.module.exports.handleConfigFileOpen (/Users/developer/.atom/packages/jekyll/lib/jekyll/utils.coffee:25:40)
    at /Users/developer/.atom/packages/jekyll/lib/jekyll/utils.coffee:20:21
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -0:00.7.0 jekyll:new-post (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "one-dark-ui",
      "volt-syntax"
    ]
  },
  "jekyll": {
    "buildCommand": [
      "/Users/developer/.rbenv/shims/jekyll",
      "build"
    ],
    "serverPort": 4000
  }
}
```
### Installed Packages

``` coffee
# User
jekyll, v1.4.0
language-liquid, v0.4.0
vim-mode, v0.65.0
volt-syntax, v0.4.0

# Dev
No dev packages
```

**Comment by Arcath** [comment] 2016-04-07 14:57
Sounds like the same problem as #48 could you post your `_config.yml` please.

**Comment by thatguychrisw** [comment] 2016-04-08 01:45
Sure thing.

# Jykell configuration
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-us'

# Website info
name: ''
description: ""

# Author's info
author: 'Christopher Willard'
# edit 'categories' in the front matter of every post to match this username
nickname: Christopher
bio: ''
location: 'for-debug'
url: 'http://for-debug/'
image: 'assets/images/me.jpg'


short_url: 'for-debug/'
google_analytics: for-debug
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: for-debug
repo: jasper
branch: master
relative_source: ../
destination: ../for-debug/
production_url:  https://for-debug
source_url:     https://for-debug

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

**Comment by Arcath** [comment] 2016-04-18 07:54
Odd, your yaml file isnt 77 lines long.

Is there any weirdness if you `cat` the file?

**Comment by xunorus** [comment] 2016-07-11 06:35
Maybe duplicate of #55 ?

**Closed** 2017-05-12 08:59 UTC
Labels: YAML Error
